import { Component, inject, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink, Router } from '@angular/router';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroArrowLeft, heroCheck, heroTrash } from '@ng-icons/heroicons/outline';
import { CategoryService } from '../../../services/category';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-category-form',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, NgIconComponent],
  viewProviders: [provideIcons({ heroArrowLeft, heroCheck, heroTrash })],
  templateUrl: './category-form.html',
})
export class CategoryForm implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private categoryService = inject(CategoryService);
  private cdr = inject(ChangeDetectorRef);

  categoryId = this.route.snapshot.paramMap.get('id');
  isEditMode = !!this.categoryId;
  isSubmitting = false;

  // 👈 Lebih bersih! Cuma nyimpen data yang beneran butuh dikirim
  category: any = {
    name: '',
    description: '',
    displayOrder: 1,
    status: true,
    itemCount: 0,
    image: null,
  };

  selectedFile: File | null = null;

  ngOnInit() {
    if (this.isEditMode) {
      this.loadCategoryData();
    } else {
      this.autoGenerateDisplayOrder();
    }
  }

  autoGenerateDisplayOrder() {
    this.categoryService.getCategories().subscribe({
      next: (res: any) => {
        if (res.data && res.data.length > 0) {
          // 1. Cari angka display_order paling besar dari semua kategori yang ada
          const maxOrder = Math.max(...res.data.map((c: any) => Number(c.display_order) || 0));

          // 2. Set angka di form jadi Angka Terbesar + 1
          this.category.displayOrder = maxOrder + 1;
        } else {
          // Kalau database masih kosong melompong, otomatis jadi nomor 1
          this.category.displayOrder = 1;
        }
        this.cdr.detectChanges(); // Tendang UI biar angkanya langsung nongol!
      },
      error: (err: any) => {
        console.error('Gagal ngecek urutan kategori:', err);
        this.category.displayOrder = 1; // Fallback aman kalau gagal
        this.cdr.detectChanges();
      },
    });
  }

  loadCategoryData() {
    this.categoryService.getCategoryById(this.categoryId!).subscribe({
      next: (res: any) => {
        const c = res.data;
        this.category.name = c.name;
        this.category.description = c.description;
        this.category.itemCount = c.products_count || 0;
        this.category.displayOrder = Number(c.display_order) || 1;
        this.category.status = c.is_active === true || c.is_active === 1 || c.is_active === '1';
        this.category.image = c.image_url || null;

        this.cdr.detectChanges();
      },
      error: (err: any) => console.error('Gagal memuat data edit kategori', err),
    });
  }

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.category.image = e.target.result;
        this.cdr.detectChanges();
      };
      reader.readAsDataURL(file);
    }
  }

  removeImage() {
    this.category.image = null;
    this.selectedFile = null;
  }

  saveCategory() {
    this.isSubmitting = true;

    const formData = new FormData();
    formData.append('name', this.category.name);
    formData.append('description', this.category.description || '');
    formData.append('display_order', this.category.displayOrder?.toString() || '1');
    formData.append('is_active', this.category.status ? '1' : '0');

    if (this.selectedFile) {
      formData.append('image', this.selectedFile);
    }

    if (this.isEditMode) {
      formData.append('_method', 'PUT');

      // PENTING: Pastikan category.service.ts kamu updateCategory-nya pakai POST seperti Products ya!
      this.categoryService.updateCategory(this.categoryId!, formData).subscribe({
        next: () => {
          this.isSubmitting = false;
          Swal.fire('Berhasil!', 'Kategori berhasil diupdate.', 'success').then(() => {
            this.router.navigate(['/categories']);
          });
        },
        error: (err: any) => {
          this.isSubmitting = false;
          Swal.fire('Oops...', 'Gagal update kategori!', 'error');
        },
      });
    } else {
      this.categoryService.createCategory(formData).subscribe({
        next: () => {
          this.isSubmitting = false;
          Swal.fire('Berhasil!', 'Kategori baru ditambahkan.', 'success').then(() => {
            this.router.navigate(['/categories']);
          });
        },
        error: (err: any) => {
          this.isSubmitting = false;
          Swal.fire('Oops...', 'Pastikan form terisi dengan benar!', 'error');
        },
      });
    }
  }

  deleteCategory() {
    Swal.fire({
      title: 'Hapus Kategori?',
      text: `Yakin ingin menghapus ${this.category.name}?`,
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#d33',
      cancelButtonColor: '#3085d6',
      confirmButtonText: 'Ya, Hapus!',
    }).then((result) => {
      if (result.isConfirmed) {
        this.categoryService.deleteCategory(this.categoryId!).subscribe({
          next: () => {
            Swal.fire('Terhapus!', 'Kategori berhasil dihapus.', 'success').then(() => {
              this.router.navigate(['/categories']);
            });
          },
          error: (err: any) =>
            Swal.fire('Gagal!', err.error?.message || 'Gagal menghapus.', 'error'),
        });
      }
    });
  }
}
